# Generated by Django 5.0.6 on 2024-06-02 01:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=users.models.user_directory_path),
        ),
    ]
