# Generated by Django 5.0.6 on 2024-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/cu_nav.png', upload_to='profile_pics'),
        ),
    ]
