# Generated by Django 5.0.6 on 2024-05-19 23:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(21)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('grade', models.CharField(max_length=20)),
                ('learning_style', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('medical_details', models.TextField(blank=True, null=True)),
                ('health_card', models.CharField(max_length=20)),
                ('parent_guardian_name', models.CharField(max_length=100)),
                ('parent_guardian_phone', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('shirt_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('goals', models.TextField()),
                ('requirements', models.TextField()),
                ('includes', models.TextField()),
                ('themes', models.TextField()),
                ('activities', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_of_operation', models.TextField()),
                ('hours_of_operation', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evaluation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('feeding', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('cognitive_comprehension', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('risk_harm_to_others', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('motor_skills', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('allergies_option', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('allergies_details', models.TextField(blank=True, null=True)),
                ('diagnosis_option', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('diagnosis_details', models.TextField(blank=True, null=True)),
                ('medications_option', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('medications_details', models.TextField(blank=True, null=True)),
                ('communication', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('communication_details', models.TextField(blank=True, null=True)),
                ('behaviour', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('behaviour_details', models.TextField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.participant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.program')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.participant')),
                ('program_space', models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='website.programspace')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationProgramSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.programspace')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reservation')),
            ],
        ),
    ]
