# Generated by Django 5.0.6 on 2024-05-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_reservation_reservation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_code',
        ),
    ]
