# Generated by Django 5.0.6 on 2024-05-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reservation_reservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
