# Generated by Django 5.0.6 on 2024-05-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_reservation_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_cost',
        ),
    ]
