# Generated by Django 5.0.6 on 2024-05-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_reservation_cost_reservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
