# Generated by Django 5.0.6 on 2024-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_reservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
