# Generated by Django 5.0.6 on 2024-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_reservation_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='medical_details',
        ),
        migrations.AlterField(
            model_name='participant',
            name='learning_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
