# Generated by Django 5.0.6 on 2024-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_participant_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
