# Generated by Django 5.0.6 on 2024-05-26 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_reservation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
