# Generated by Django 5.0.6 on 2024-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_participant_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.CharField(max_length=255)),
                ('founder_title', models.CharField(max_length=255)),
                ('founder_summary', models.CharField(max_length=255)),
                ('founder_quote', models.CharField(max_length=255)),
                ('mission', models.CharField(max_length=255)),
                ('values', models.CharField(max_length=255)),
            ],
        ),
    ]
