# Generated by Django 5.0.6 on 2024-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='founder_quote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='founder_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='values',
            field=models.TextField(null=True),
        ),
    ]
