# Generated by Django 5.0.6 on 2024-05-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_company_address_alter_company_founder_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
