# Generated by Django 5.0.6 on 2024-05-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_company_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='emergency_contact_relationship',
        ),
        migrations.AlterField(
            model_name='participant',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3),
        ),
    ]
