# Generated by Django 5.0.6 on 2024-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_participant_emergency_contact_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
