# Generated by Django 5.0.6 on 2024-06-07 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_program_author_program_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
